"""add unique_hash nullable

Revision ID: 7c29f42df2e2
Revises: e23ccdf18a0d
Create Date: 2026-04-23 20:14:43.057754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c29f42df2e2'
down_revision: Union[str, None] = 'e23ccdf18a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('unique_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_transactions_unique_hash'), 'transactions', ['unique_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_unique_hash'), table_name='transactions')
    op.drop_column('transactions', 'unique_hash')
    # ### end Alembic commands ###
